---
width: 32
height: 32

seed: python

turns: 6000
timeout: 25
wait: true

respawn: 10

food:
  value: 5
  lifetime: 50

players:
  - Python Example:
      type: custom
      executable: python
      arguments: src/main.py

  - Easy:
      type: builtin
      difficulty: easy

  - Medium:
      type: builtin
      difficulty: medium

  - Hard:
      type: builtin
      difficulty: hard
