---
width: 32
height: 32

seed: java

turns: 6000
timeout: 25
wait: true

respawn: 10

food:
  value: 5
  lifetime: 50

players:
  - Java Example:
      type: custom
      executable: java
      arguments:
        - -jar
        - Example.jar

  - Easy:
      type: builtin
      difficulty: easy

  - Medium:
      type: builtin
      difficulty: medium

  - Hard:
      type: builtin
      difficulty: hard
