# Default Snakes! Configuration
---
width: 16
height: 16

# Game settings
turns: 500
turnsPerSecond: 0

seed: the holy grail

respawn: 2

# Food configuration
food:
  value: 5
  lifetime: 0
  count: 1

# Player configurations
players:
  # - Ferris:
  #     type: custom
  #     silent: false
  #     color: venetian red
  #     cmd: examples/ferris.exe

  - Keygan:
      type: keyboard
      timeout: 250
      wait: false
      keys:
        north: w
        west: a
        south: s
        east: d
#   - Easy:
#       type: builtin
#       difficulty: easy
#       color: green # you can choose colors

#   - Medium:
#       type: builtin
#       color: bluetiful # you can use Crayola color names
#       difficulty: medium

#   - Hard:
#       type: builtin
#       color: e6bc5c # you can also use hex strings (with or without a #)
#       difficulty: hard
