---
width: 32
height: 32

seed: rust

turns: 6000
timeout: 25
wait: true

respawn: 10

food:
  value: 5
  lifetime: 50

players:
  - Rust Example:
      type: custom
      executable: target\debug\example.exe

  - Easy:
      type: builtin
      difficulty: easy

  - Medium:
      type: builtin
      difficulty: medium

  - Hard:
      type: builtin
      difficulty: hard
