name: Discord Notification

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@0.4.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "<@&1001811147831386182>, Snakes! {{ EVENT_PAYLOAD.release.tag_name }} has been released. Download it here {{ EVENT_PAYLOAD.release.html_url }}"
